import type { Metadata } from "next";
import Head from 'next/head';
import { Inter, Nunito_Sans, Poppins } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import MainNavbar from "./main-components/MainNavbar";
import Footer from "./main-components/Footer"
import Provider from "./store/provider";
import ScrollToTopButton from "./main-components/BackToTop";
import MobileNavbar from "./main-components/MobileNavbar";
import SignUpModal from "./main-components/SignUpModal"
import AddToCartModal from "./main-components/AddToCartModal"
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"]
});

export const metadata: Metadata = {
  title: "Ujenzi Africa",
  description: "Generated by create next app",
  icons: {
    icon: "https://d1nhio0ox7pgb.cloudfront.net/_img/g_collection_png/standard/512x512/hammer.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>
          <MainNavbar />
          <MobileNavbar/>
          <SignUpModal/>
          <div style={{paddingTop: "237px"}} >
            {children}
          </div>
          <ScrollToTopButton />
          <Footer />
          <AddToCartModal/>
        </Provider>
      </body>
    </html>
  );
}
